name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch: # Permite rodar manualmente pelo GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instala Python e dependências
        run: |
          sudo apt update
          sudo apt install -y python3.12-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instala Playwright
        run: |
          source venv/bin/activate
          playwright install --with-deps

      - name: Executa os testes com Pytest
        run: |
          source venv/bin/activate
          HEADLESS=true pytest tests/ --html=report.html --self-contained-html

      - name: Publica o report como artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            report.html
            screenshots/
